admin: Add support for comment search by Thread URL in admin interface
isso-comments/isso pull request #1020
Opened 2024-04-27 22:05 UTC by pkvach

## Checklist
- [x] All new and existing **tests are passing**
- [ ] I have added an entry to `CHANGES.rst` because this is a user-facing change or an important bugfix
- [x] I have written **proper commit message(s)**
      

## What changes does this Pull Request introduce?

The main theme of the changes is to enhance the comment search functionality in the admin interface. The changes allow searching for comments not only by comment URL but also by thread URL.

## Why is this necessary?

- https://github.com/isso-comments/isso/issues/642
- https://github.com/isso-comments/isso/pull/1000

2024-04-29 01:02 UTC, ix5 requested changes
Thanks for the PR!

Could we perhaps find a better way to convey to admins that they can enter both thread and individual comment URLs?

Also, would it make sense to make the search field a bit smarter and just let it accept plain numbers (for comment ids) as well?

2024-04-29 18:09 UTC, pkvach commented
> Thanks for the PR!

I'm happy to help :)

> Could we perhaps find a better way to convey to admins that they can enter both thread and individual comment URLs?

There is an option to add a tooltip with explanatory text. This will not take up too much space.

> Also, would it make sense to make the search field a bit smarter and just let it accept plain numbers (for comment ids) as well?

Then we will definitely need explanatory text and will have to give up `<input type=“url”>`.

2024-04-29 20:19 UTC, ix5 commented
> > Could we perhaps find a better way to convey to admins that they can enter both thread and individual comment URLs?
> 
> There is an option to add a tooltip with explanatory text. This will not take up too much space.

Good idea. Something like `<abbr>` that pops on mouseover will not work on mobile, but if you have a good solution, go for it.

> > Also, would it make sense to make the search field a bit smarter and just let it accept plain numbers (for comment ids) as well?
> 
> Then we will definitely need explanatory text and will have to give up `<input type=“url”>`.

On second thought, let's not implement the "smart" search and leave it as is. It would just be confusing.

2024-05-02 22:29 UTC, pkvach commented
I added a tooltip with help text next to the search field.
It's ready for review.

2024-05-03 17:09 UTC, ix5 reviewed
Nice, the tooltip is really useful.

I'd just want it a bit more integrated/look alike the rest of the surrounding buttons, so that it's clearer it is clickable.

Current:
![Screenshot from 2024-05-03 19-03-18](https://github.com/isso-comments/isso/assets/10212877/fe7e04d9-7d14-433b-b5c3-4288b3943bc4)

With more prominent border and shadow:
![Screenshot from 2024-05-03 19-02-55](https://github.com/isso-comments/isso/assets/10212877/68146451-56ea-43d0-a189-f0384d5a75e5)

2024-05-03 17:09 UTC, ix5 commented on isso/css/admin.css
> +  from {opacity: 0;}
single trailing whitespace here
```diff
-  from {opacity: 0;} 
+  from {opacity: 0;}
```

2024-05-04 07:11 UTC, pkvach commented
> Nice, the tooltip is really useful.
> 
> I'd just want it a bit more integrated/look alike the rest of the surrounding buttons, so that it's clearer it is clickable.
> 
> Current: ![Screenshot from 2024-05-03 19-03-18](https://private-user-images.githubusercontent.com/10212877/327829576-fe7e04d9-7d14-433b-b5c3-4288b3943bc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MDY3NTUsIm5iZiI6MTcxNDgwNjQ1NSwicGF0aCI6Ii8xMDIxMjg3Ny8zMjc4Mjk1NzYtZmU3ZTA0ZDktN2QxNC00MzNiLWI1YzMtNDI4OGIzOTQzYmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDA3MDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MjRjMTNhNzJlYjI0ZGVmODZlYmI5ODQ2MWIyNWY2NTExYjViMjJhMWUzMjIyMTVhYjc3NDEyMDRhMDlkZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tca3dYDMLf_VcDAx2-8ywA4oHpAR1A4zUenqPf6QAAw)
> 
> With more prominent border and shadow: ![Screenshot from 2024-05-03 19-02-55](https://private-user-images.githubusercontent.com/10212877/327829567-68146451-56ea-43d0-a189-f0384d5a75e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MDY3NTUsIm5iZiI6MTcxNDgwNjQ1NSwicGF0aCI6Ii8xMDIxMjg3Ny8zMjc4Mjk1NjctNjgxNDY0NTEtNTZlYS00M2QwLWExODktZjAzODRkNWE3NWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDA3MDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMzY1ZGQyNTBiMWRjMmM3ZjdjYTNkNTBiODlkMGU5YzFmZGQwZjU1YjgwNDc1MzQyZmY1NzgzY2M4YTM5M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9yiJPAUmyQaRIjMSOUTcY-svKPvjR0DW6-j4LKsQUXY)

Thank you for the review and a nice addition.
I made the suggested changes and did squash commits.

2024-05-04 18:40 UTC, ix5 approved these changes

2024-05-04 18:41 UTC, merged

2024-05-04 18:41 UTC, ix5 commented
Merged, thanks!